### ISSUE TITLE
Pom cleanup in all the projects

### ISSUE THREAD

**Issue by krystofNovotny** [WrenSecurity/wrenidm#112]
It is necessary to remove  `<extensions>true</extensions>` from all the poms using Wrensec-parent >= 3.2.0 and then make sure that correct manifest is generated.

**Comment by pavelhoral** [comment]
I am not able to build openidm-core module locally due to the bundle config change. We should address this ASAP.

**Comment by karelmaxa** [comment]
Packaging of all modules (except UI modules) has been switched to the jar packaging. So the result jars are being created through maven-jar-plugin. Packaging of UI modules have not been switched because of Include-Resource directive.

Some other minor changes have been done:

* Updated license headers of pom files,
* Fixed site build,
* Remove some deprecated stuff.
